#ifndef MATH_ALGEBRA_LINEAR_CONFIG_HPP
#define MATH_ALGEBRA_LINEAR_CONFIG_HPP

#ifndef ALLOW_INDEX_CHECKING
#define ALLOW_INDEX_CHECKING 1
#endif

#ifndef ALLOW_NEGATIVE_INDEX
#define ALLOW_NEGATIVE_INDEX 1
#endif

#ifndef ALLOW_MATH_OPERATIONS
#define ALLOW_MATH_OPERATIONS 1
#endif



#endif // MATH_ALGEBRA_LINEAR_CONFIG_HPP